#game settings
RES = WIDTH, HEIGHT = 1600, 900
FPS = 60
SCROLL_SPEED = 8  
GRAVITY = 1

# caco settings
CACO_POS = WIDTH // 4,HEIGHT//3
CACO_SCALE = 1.45
CACO_ANIMATION_TIME = 150
JUMP_VALUE = -16
JUMP_ANGLE = 30

# Ground
GROUND_HEIGHT = HEIGHT//12
GROUND_Y = HEIGHT - GROUND_HEIGHT

# Pipe settings
PIPE_WIDTH = 150 * CACO_SCALE
PIPE_HEIGHT = HEIGHT
DISTANCE_BETWEEN_PIPES = 650
GAP_HEIGHT = 340
HALF_GAP_HEIGHT = GAP_HEIGHT // 2